### ISSUE TITLE
Merge-in resources from US-focused article on tech coops?

### ISSUE THREAD

**Issue by rmharrison** [hng/tech-coops#4]
Hello! Have drafted an article on the (US-focused) resources I've come across.

Much overlap with you, so hopefully can avoid re-investing the wheel. Would you be open to a PR to merge the diffs?

Draft article (feedback welcome): https://medium.com/@rmharrison/how-to-find-technical-worker-cooperatives-b253c7a7c6ef

**Comment by hng** [comment]
Yes please! Just go ahead! :)

But please sent one PR for every link.
