### ISSUE TITLE
Are PRs to add orgs still be accepted?

### ISSUE THREAD

**Issue by shonfeder** [hng/tech-coops#78]
I've noticed that there is growing backlog of PRs adding entries for co-ops. Is there a freeze on adding new co-ops? Do you need additional help maintaining this repo?

As PRs build up we increase the likelihood of merge conflicts, since they are all editing the same file. So I'm mainly concerned with ensuring we avoid creating more work for you or the contributors.

**Comment by trivigy** [comment]
@hng I will help you maintain and PR reviews. If you are willing to add contributors.
